// <auto-generated />
namespace GearHunter.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testingifnewmigrationwillwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingifnewmigrationwillwork));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181118148_testing if new migration will work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
